### ISSUE TITLE
feature request: support placeholders and values

### ISSUE THREAD

**Issue by ghost** [danabr/jsI18n#3]
First I would like to thank you for this effective and easy JS.

About the feature:
This for example works great and changes innerHtml
`<label for="exactTitle" data-trans="(exact?)">Exact ?</label>`
and this too
`<button data-trans="(search)">Search</button>`

But I would like to do the same for inputs:
`<input name="desc" value="" placeholder="Description">`

for example something like:
`<input data-trans="(description)" placeholder="Description">`
(In my example I need it to change placeholder, but value also could be beneficent.
Thanks a lot!

**Comment by ghost** [comment]
I imagine something like

`<input data-trans-ph="(description)" placeholder="Description">`

or 

`<input data-trans-v="(description)" value="Description">`

**Comment by danabr** [comment]
Hi, doesn't [attribute translation](https://github.com/danabr/jsI18n#attribute-translation) work for your use case?

**Comment by ghost** [comment]
Oh I missed that one and its clear in readme.

It seems to be the one as intended. I didn't test but closing this. 

Thanks a lot
